name: number_trivia
description: TDD Clean Architecture for Flutter

version: 1.0.0+1

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  dartz: ^0.10.1
  data_connection_checker: ^0.3.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  http: ^0.13.5
  shared_preferences: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0

flutter:
  uses-material-design: true